export const SET_LOADER = 'App/SET_LOADER';

export const LOAD_MERCHANTS_LIST_SEND = 'App/LOAD_MERCHANTS_LIST_SEND';
export const LOAD_MERCHANTS_LIST_SUCCESS = 'App/LOAD_MERCHANTS_LIST_SUCCESS';

export const UPDATE_MERCHANT_SEND = 'App/UPDATE_MERCHANT_SEND';
export const UPDATE_MERCHANT_SUCCESS = 'App/UPDATE_MERCHANT_SUCCESS';

export const REMOVE_MERCHANT_SEND = 'App/REMOVE_MERCHANT_SEND';
export const REMOVE_MERCHANT_SUCCESS = 'App/REMOVE_MERCHANT_SUCCESS';
